---
title: 'Predicting Flake Mass: A View from Machine Learning. Lithic Technology'
author: "Guillermo Bustos-Pérez"
date: "7/3/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1) Load packages, read and check data    

The data is available in this repository as a **.csv** file. Please note that original data uses **","** as decimal marker instead of using **"."**. Thus, it is required to use the function **read_csv2**.  

```{r}
# Load packages  
library(tidyverse)
library(kableExtra)
```
```{r}
# Read in data
Reg_Data <- read.csv2("Data.csv")
```




```{r, eval=FALSE}
Reg_Data_2 <- Reg_Data_2 %>% 
  mutate(Log_Weight = log10(Weight),
         Log_Thick = log10(MeanThick),
         Log_SD_Thick = log10(SDThick),
         Log_Plat = log10(Surface.Plat),
         Log_Plat_2 = log10(Surf_Plat_II),
         Log_Plat_De = log10(`Platform Deepnes`),
         Log_EPA = log10(EPA),
         Log_IPA = log10(IPA)) 
```


## References   


